### ISSUE TITLE
Can session be sped up by not creating a header/cookie dict?

### ISSUE THREAD

**Issue by Tbaste10** [MarkReedZ/mrhttp#12]
The sessions benchmark is repeated twice in the README and the correct value is the slower one.  I noticed that when a session is required the header and cookies are loaded.  Do we have to do this? It should be much faster to scan for cookie in the header then directly scan for the session key?

```c
  if(!self->py_headers) self->py_headers = Request_decode_headers(self);
  if(!self->py_cookies) self->py_cookies = Request_decode_cookies(self);
```

**Comment by MarkReedZ** [comment]
Try a micro benchmark of that code.  Grab the rdtsc function from parser.c and move it to common.h then wrap those calls.  But yeah it should be faster unless the headers and cookies need to be parsed anyway.  I'll think about it.

**Comment by Tbaste10** [comment]
Those calls are about 4k cycles on my machine.  I'll add a function Request_load_session instead of load_cookies.

**Comment by MarkReedZ** [comment]
Sounds good then.  When you benchmark the session don't forget to add a session to memcached.

```python
from pymemcache.client.base import Client
c = Client(('localhost', 11211))
c.set( "mrsession43709dd361cc443e976b05714581a7fb",'{"user":"Mark"}' )
```

**Comment by MarkReedZ** [comment]
I went ahead and implemented this as described - that section of code is 40x faster and the benchmark is 15% faster.
